changelog:
  categories:
    - title: "⚡ Breaking Changes"
      labels:
        - "breaking-change"
    - title: "🌟New features and non-breaking changes"
      labels:
        - "major"
        - "feature"
    - title: "🌟 Minor Changes"
      labels:
        - "enhancement"
    - title: "📜 Documentation updates"
      labels:
        - "documentation"
    - title: "🐛 Bug and hot fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🚒 Deprecations"
      labels:
        - "deprecated"
    - title: "🔧 Maintenance"
      labels:
        - "internal"
        - "dependencies"
