export const articlesData =[
	{
		"id": 1,
		"company": "DEMO Company",
		"reference": "x",
		"description": "test X",
		"piece-to-be-replenish": "No",
		"status": "IN PROGRESS",
		"length": 100,
		"width": 100,
		"height": 100,
		"weight": "1"
	},
	{
		"id": 2,
		"company": "DEMO Company",
		"reference": "NB0001",
		"description": "NB 00001",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 10,
		"height": 10,
		"weight": "1"
	},
	{
		"id": 3,
		"company": "DEMO Company",
		"reference": "101-002",
		"description": "Пошехонский сыр",
		"piece-to-be-replenish": "No",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 20,
		"height": 5,
		"weight": "0,2"
	},
	{
		"id": 4,
		"company": "DEMO Company",
		"reference": "101-001",
		"description": "Сыр Адыгейский",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 15,
		"height": 3,
		"weight": "0,3"
	},
	{
		"id": 5,
		"company": "TEST2",
		"reference": "ARTSOCTEST2",
		"description": "Libellé",
		"piece-to-be-replenish": "No",
		"status": "IN PROGRESS",
		"length": 1,
		"width": 1,
		"height": 1,
		"weight": "1"
	},
	{
		"id": 6,
		"company": "DEMO Company",
		"reference": "1000057",
		"description": "Parasol Bugara Gris 117792X - 1/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 15,
		"width": 60,
		"height": 80,
		"weight": "8"
	},
	{
		"id": 7,
		"company": "DEMO Company",
		"reference": "1000056",
		"description": "Parasol Bugara Gris 117792 - 1/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 15,
		"width": 60,
		"height": 200,
		"weight": "13"
	},
	{
		"id": 8,
		"company": "DEMO Company",
		"reference": "1000055",
		"description": "Parasol Bugara Sable 117793X - 2/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 15,
		"width": 60,
		"height": 80,
		"weight": "8"
	},
	{
		"id": 9,
		"company": "DEMO Company",
		"reference": "1000054",
		"description": "Parasol Bugara Sable 117793 - 1/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 15,
		"width": 50,
		"height": 200,
		"weight": "13"
	},
	{
		"id": 10,
		"company": "DEMO Company",
		"reference": "34569",
		"description": "Piscine Gonflable Intex Koh Tao Verte",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 6,
		"height": 23,
		"weight": "1,03"
	},
	{
		"id": 11,
		"company": "DEMO Company",
		"reference": "1000053",
		"description": "SALONB005 - 4/4",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 19,
		"width": 57,
		"height": 125,
		"weight": "19"
	},
	{
		"id": 12,
		"company": "DEMO Company",
		"reference": "1000052",
		"description": "SALONB004 - 3/4",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 22,
		"width": 55,
		"height": 71,
		"weight": "14"
	},
	{
		"id": 13,
		"company": "DEMO Company",
		"reference": "1000051",
		"description": "SALONB003 - 2/4",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 22,
		"width": 55,
		"height": 71,
		"weight": "14"
	},
	{
		"id": 14,
		"company": "DEMO Company",
		"reference": "1000050",
		"description": "SALONB001 - 1/4",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 8,
		"width": 52,
		"height": 83,
		"weight": "7"
	},
	{
		"id": 15,
		"company": "DEMO Company",
		"reference": "1000049",
		"description": "R033 - 2/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 79,
		"width": 79,
		"height": 136,
		"weight": "41,4"
	},
	{
		"id": 16,
		"company": "DEMO Company",
		"reference": "1000048",
		"description": "R032 - 1/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 106,
		"width": 82,
		"height": 93,
		"weight": "30,4"
	},
	{
		"id": 17,
		"company": "DEMO Company",
		"reference": "1000047",
		"description": "Tinos Tabourets 107104 - 2/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 74,
		"width": 21,
		"height": 95,
		"weight": "27"
	},
	{
		"id": 18,
		"company": "DEMO Company",
		"reference": "1000046",
		"description": "Tinos Bar 107104 - 1/2",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 11,
		"width": 146,
		"height": 77,
		"weight": "33"
	},
	{
		"id": 19,
		"company": "DEMO Company",
		"reference": "34568",
		"description": "Coussin imprimé Millie",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 40,
		"width": 40,
		"height": 5,
		"weight": "0,5"
	},
	{
		"id": 20,
		"company": "DEMO Company",
		"reference": "34567",
		"description": "Housse de chaise Sofia",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 26,
		"width": 38,
		"height": 2,
		"weight": "0,4"
	},
	{
		"id": 21,
		"company": "DEMO Company",
		"reference": "34566",
		"description": "Housse de fauteuil Sofia",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 28,
		"width": 45,
		"height": 4,
		"weight": "0,9"
	},
	{
		"id": 22,
		"company": "DEMO Company",
		"reference": "34565",
		"description": "Coussin Sofia",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 40,
		"width": 40,
		"height": 3,
		"weight": "0,23"
	},
	{
		"id": 23,
		"company": "DEMO Company",
		"reference": "34564",
		"description": "STALACTITE SOLAIRE LED-6M",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 23,
		"width": 8,
		"height": 9,
		"weight": "0,36"
	},
	{
		"id": 24,
		"company": "DEMO Company",
		"reference": "34563",
		"description": "POT LUMINEUX CARRE Blanc H=50cm",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 31,
		"width": 31,
		"height": 52,
		"weight": "2,5"
	},
	{
		"id": 25,
		"company": "DEMO Company",
		"reference": "34562",
		"description": "Nénuphar flottant LED Couleur changeante",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 16,
		"height": 16,
		"weight": "0,135"
	},
	{
		"id": 26,
		"company": "DEMO Company",
		"reference": "34561",
		"description": "Nénuphar flottant LED Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 16,
		"height": 16,
		"weight": "0,135"
	},
	{
		"id": 27,
		"company": "DEMO Company",
		"reference": "34560",
		"description": "LANTERNE SOLAIRE METAL BLANC GRAND",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 18,
		"height": 35,
		"weight": "2,2"
	},
	{
		"id": 28,
		"company": "DEMO Company",
		"reference": "34559",
		"description": "LANTERNE SOLAIRE METAL BLANC PETIT",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 13,
		"height": 20,
		"weight": "0,56"
	},
	{
		"id": 29,
		"company": "DEMO Company",
		"reference": "34558",
		"description": "LANTERNE SOLAIRE IMITATION ROTIN",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 15,
		"width": 15,
		"height": 19,
		"weight": "0,38"
	},
	{
		"id": 30,
		"company": "DEMO Company",
		"reference": "34557",
		"description": "Lanterne cylindrique LED Vert",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 12,
		"height": 18,
		"weight": "0,4"
	},
	{
		"id": 31,
		"company": "DEMO Company",
		"reference": "34556",
		"description": "Lanterne cylindrique LED Fuchsia",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 12,
		"height": 18,
		"weight": "0,4"
	},
	{
		"id": 32,
		"company": "DEMO Company",
		"reference": "34555",
		"description": "Lanterne cylindrique LED Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 12,
		"height": 18,
		"weight": "0,4"
	},
	{
		"id": 33,
		"company": "DEMO Company",
		"reference": "34554",
		"description": "Lanterne cylindrique LED Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 12,
		"height": 25,
		"weight": "0,5"
	},
	{
		"id": 34,
		"company": "DEMO Company",
		"reference": "34553",
		"description": "LANTERNE SOL. CYLINDRIQUE ARGENT GM",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 12,
		"height": 25,
		"weight": "0,5"
	},
	{
		"id": 35,
		"company": "DEMO Company",
		"reference": "34552",
		"description": "LANTERNE KIOSQUE SOL. METAL BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 17,
		"height": 34,
		"weight": "1,1"
	},
	{
		"id": 36,
		"company": "DEMO Company",
		"reference": "34551",
		"description": "LANTERNE KIOSQUE SOL. METAL ARGENT",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 17,
		"height": 34,
		"weight": "1,1"
	},
	{
		"id": 37,
		"company": "DEMO Company",
		"reference": "34550",
		"description": "LANTERNE JARDIN CLASSIQUE NOIRE LED",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 29,
		"width": 25,
		"height": 8,
		"weight": "0,78"
	},
	{
		"id": 38,
		"company": "DEMO Company",
		"reference": "34549",
		"description": "LANTERNE CERAMIQUE LIBELLULE VERT",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 20,
		"height": 30,
		"weight": "1,1"
	},
	{
		"id": 39,
		"company": "DEMO Company",
		"reference": "34548",
		"description": "LANTERNE CERAMIQUE LIBELLULE ROUGE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 20,
		"height": 30,
		"weight": "1,1"
	},
	{
		"id": 40,
		"company": "DEMO Company",
		"reference": "34547",
		"description": "LANTERNE CERAMIQUE LIBELLULE GRIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 20,
		"height": 30,
		"weight": "1,1"
	},
	{
		"id": 41,
		"company": "DEMO Company",
		"reference": "34546",
		"description": "LANTERNE CERAMIQUE COEUR GRIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 20,
		"width": 20,
		"height": 30,
		"weight": "1,05"
	},
	{
		"id": 42,
		"company": "DEMO Company",
		"reference": "34545",
		"description": "GUIRLANDE SOLAIRE LED-5M BLEU",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 8,
		"height": 9,
		"weight": "0,25"
	},
	{
		"id": 43,
		"company": "DEMO Company",
		"reference": "34544",
		"description": "GUIRLANDE SOLAIRE LED-5M BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 8,
		"height": 9,
		"weight": "0,25"
	},
	{
		"id": 44,
		"company": "DEMO Company",
		"reference": "34543",
		"description": "GUIRLANDE SOLAIRE LED-16M BLEU",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 10,
		"height": 13,
		"weight": "0,75"
	},
	{
		"id": 45,
		"company": "DEMO Company",
		"reference": "34542",
		"description": "GUIRLANDE SOLAIRE LED-16M BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 10,
		"height": 13,
		"weight": "0,75"
	},
	{
		"id": 46,
		"company": "DEMO Company",
		"reference": "34541",
		"description": "GUIRLANDE SOLAIRE LED-10M MUTI",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 10,
		"height": 10,
		"weight": "0,5"
	},
	{
		"id": 47,
		"company": "DEMO Company",
		"reference": "34540",
		"description": "GUIRLANDE SOLAIRE LED-10M BLEU",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 10,
		"height": 10,
		"weight": "0,5"
	},
	{
		"id": 48,
		"company": "DEMO Company",
		"reference": "34539",
		"description": "GUIRLANDE SOLAIRE LED-10M BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 10,
		"height": 10,
		"weight": "0,5"
	},
	{
		"id": 49,
		"company": "DEMO Company",
		"reference": "34538",
		"description": "GUIRLANDE SOLAIRE LED MULTI-5M",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 13,
		"width": 8,
		"height": 9,
		"weight": "0,25"
	},
	{
		"id": 50,
		"company": "DEMO Company",
		"reference": "34537",
		"description": "GUIRLANDE SOLAIRE LED MULTI -16M",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 10,
		"height": 13,
		"weight": "0,75"
	},
	{
		"id": 51,
		"company": "DEMO Company",
		"reference": "34536",
		"description": "GUIRLANDE SOLAIRE LAMPIONS CHINOIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 22,
		"width": 7,
		"height": 11,
		"weight": "0,3"
	},
	{
		"id": 52,
		"company": "DEMO Company",
		"reference": "34535",
		"description": "GUIRLANDE PAPILLONS MIROIRS MULTI",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 9,
		"width": 9,
		"height": 17,
		"weight": "0,4"
	},
	{
		"id": 53,
		"company": "DEMO Company",
		"reference": "34534",
		"description": "GUIRLANDE PAPILLONS MIROIRS BLANCS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 9,
		"width": 9,
		"height": 17,
		"weight": "0,4"
	},
	{
		"id": 54,
		"company": "DEMO Company",
		"reference": "34533",
		"description": "GUIRLANDE PAPILLONS FO MULTI",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 16,
		"width": 13,
		"height": 12,
		"weight": "0,34"
	},
	{
		"id": 55,
		"company": "DEMO Company",
		"reference": "34532",
		"description": "GUIRLANDE PAPILLONS FO BLANCHE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 16,
		"width": 13,
		"height": 12,
		"weight": "0,34"
	},
	{
		"id": 56,
		"company": "DEMO Company",
		"reference": "34531",
		"description": "GUIRLANDE LIBELLULES SOLAIRE RGB",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 12,
		"width": 9,
		"height": 21,
		"weight": "0,42"
	},
	{
		"id": 57,
		"company": "DEMO Company",
		"reference": "34530",
		"description": "GUIRLANDE FETE MULTICOLORE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 30,
		"width": 21,
		"height": 9,
		"weight": "0,001"
	},
	{
		"id": 58,
		"company": "DEMO Company",
		"reference": "34529",
		"description": "GUIRLANDE FETE BLANCHE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 30,
		"width": 21,
		"height": 9,
		"weight": "0,968"
	},
	{
		"id": 59,
		"company": "DEMO Company",
		"reference": "34528",
		"description": "GUIRLANDE ARROSOIRS METAL MARRON",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 22,
		"width": 20,
		"height": 8,
		"weight": "0,6"
	},
	{
		"id": 60,
		"company": "DEMO Company",
		"reference": "34527",
		"description": "GUIRLANDE 7 CUBES ROTIN MULTI.",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 27,
		"width": 23,
		"height": 8,
		"weight": "0,5"
	},
	{
		"id": 61,
		"company": "DEMO Company",
		"reference": "34526",
		"description": "GUIRLANDE 7 BOULES ROTIN MULTI.",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 26,
		"width": 20,
		"height": 7,
		"weight": "0,46"
	},
	{
		"id": 62,
		"company": "DEMO Company",
		"reference": "34525",
		"description": "GUIRLANDE 4 TUBES COLORES",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 11,
		"width": 11,
		"height": 47,
		"weight": "1,12"
	},
	{
		"id": 63,
		"company": "DEMO Company",
		"reference": "34524",
		"description": "GUIRLANDE 14 FRAISES ROUGES",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 12,
		"height": 7,
		"weight": "0,6"
	},
	{
		"id": 64,
		"company": "DEMO Company",
		"reference": "34523",
		"description": "GUIRLANDE 14 COCCINELLES ROUGES",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 17,
		"width": 12,
		"height": 6,
		"weight": "0,48"
	},
	{
		"id": 65,
		"company": "DEMO Company",
		"reference": "34522",
		"description": "GLDE NOIRE B22-6M CAOUTCHOUC-10D",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 33,
		"width": 26,
		"height": 11,
		"weight": "2"
	},
	{
		"id": 66,
		"company": "DEMO Company",
		"reference": "34521",
		"description": "GLDE LAMPIONS RONDS CHINOIS MULTI",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 11,
		"width": 7,
		"height": 19,
		"weight": "0,4"
	},
	{
		"id": 67,
		"company": "DEMO Company",
		"reference": "34520",
		"description": "GLDE B22 LED-6M CAOUTCHOUC-10D",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 33,
		"width": 26,
		"height": 11,
		"weight": "2"
	},
	{
		"id": 68,
		"company": "DEMO Company",
		"reference": "34519",
		"description": "ENSEMB 4 PIQUES JARDIN CYLINDRE RGB",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 11,
		"width": 8,
		"height": 40,
		"weight": "2,4"
	},
	{
		"id": 69,
		"company": "DEMO Company",
		"reference": "34518",
		"description": "ENSEMB 4 PIQUES JARDIN CYLINDRE BLC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 11,
		"width": 8,
		"height": 40,
		"weight": "2,4"
	},
	{
		"id": 70,
		"company": "DEMO Company",
		"reference": "34517",
		"description": "BOULE RONDE Blanc ø=40cm",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 41,
		"weight": "1,8"
	},
	{
		"id": 71,
		"company": "DEMO Company",
		"reference": "34516",
		"description": "BOULE RONDE Blanc ø=20cm",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 21,
		"width": 21,
		"height": 23,
		"weight": "0,5"
	},
	{
		"id": 72,
		"company": "DEMO Company",
		"reference": "34515",
		"description": "BOUGIE SOLAIRE SCINTILLANTE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 8,
		"width": 8,
		"height": 12,
		"weight": "0,08"
	},
	{
		"id": 73,
		"company": "DEMO Company",
		"reference": "34514",
		"description": "4 FLEURS DECO A PILES",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 17,
		"width": 17,
		"height": 39,
		"weight": "0,1"
	},
	{
		"id": 74,
		"company": "DEMO Company",
		"reference": "34513",
		"description": "Lot de 3 bougies LED Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 25,
		"width": 9,
		"height": 27,
		"weight": "0,97"
	},
	{
		"id": 75,
		"company": "DEMO Company",
		"reference": "34512",
		"description": "Lot de 3 bougies LED Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 25,
		"width": 9,
		"height": 27,
		"weight": "0,97"
	},
	{
		"id": 76,
		"company": "DEMO Company",
		"reference": "34511",
		"description": "10 LAMPES LED FILAMENT B22 MULTI",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 18,
		"width": 7,
		"height": 25,
		"weight": "0,5"
	},
	{
		"id": 77,
		"company": "DEMO Company",
		"reference": "34510",
		"description": "Paire de voilage droit (H160 cm) Lignato Mandarine",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,18"
	},
	{
		"id": 78,
		"company": "DEMO Company",
		"reference": "34509",
		"description": "Paire de voilage droit (H160 cm) Lignato Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,18"
	},
	{
		"id": 79,
		"company": "DEMO Company",
		"reference": "34508",
		"description": "Paire de voilage droit (H160 cm) Lignato Bois de rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,18"
	},
	{
		"id": 80,
		"company": "DEMO Company",
		"reference": "34507",
		"description": "Paire de voilage droit (H160 cm) Lignato Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,18"
	},
	{
		"id": 81,
		"company": "DEMO Company",
		"reference": "34506",
		"description": "Paire de voilage droit (H160 cm) Lignato Anis",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,18"
	},
	{
		"id": 82,
		"company": "DEMO Company",
		"reference": "34505",
		"description": "Paire de voilage droit (H120 cm) Tessa Prune",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,09"
	},
	{
		"id": 83,
		"company": "DEMO Company",
		"reference": "34504",
		"description": "Paire de voilage droit (H120 cm) Tessa Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,09"
	},
	{
		"id": 84,
		"company": "DEMO Company",
		"reference": "34503",
		"description": "Paire de voilage droit (H120 cm) Tessa Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,09"
	},
	{
		"id": 85,
		"company": "DEMO Company",
		"reference": "34502",
		"description": "Paire de voilage droit (H120 cm) Tessa Vert Bambou",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,09"
	},
	{
		"id": 86,
		"company": "DEMO Company",
		"reference": "34501",
		"description": "Paire de voilage droit (H120 cm) Helena Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,12"
	},
	{
		"id": 87,
		"company": "DEMO Company",
		"reference": "34500",
		"description": "Paire de voilage droit (H120 cm) Helena Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,12"
	},
	{
		"id": 88,
		"company": "DEMO Company",
		"reference": "34499",
		"description": "Voilage à oeillets jacquard Metissage Orange",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,29"
	},
	{
		"id": 89,
		"company": "DEMO Company",
		"reference": "34498",
		"description": "Voilage à oeillets jacquard Leana Bordeaux",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,45"
	},
	{
		"id": 90,
		"company": "DEMO Company",
		"reference": "34497",
		"description": "Voilage à oeillets jacquard Leana Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,45"
	},
	{
		"id": 91,
		"company": "DEMO Company",
		"reference": "34496",
		"description": "Voilage à oeillets jacquard Leana Beige",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,45"
	},
	{
		"id": 92,
		"company": "DEMO Company",
		"reference": "34495",
		"description": "Voilage à oeillets Fantaisie Taupe",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,285"
	},
	{
		"id": 93,
		"company": "DEMO Company",
		"reference": "34494",
		"description": "Voilage à oeillets Fantaisie Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,285"
	},
	{
		"id": 94,
		"company": "DEMO Company",
		"reference": "34493",
		"description": "Voilage à illets Emma Ivoire",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,58"
	},
	{
		"id": 95,
		"company": "DEMO Company",
		"reference": "34492",
		"description": "Voilage à illets Noa Jaune",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,44"
	},
	{
		"id": 96,
		"company": "DEMO Company",
		"reference": "34491",
		"description": "Voilage à illets Noa Corail",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,44"
	},
	{
		"id": 97,
		"company": "DEMO Company",
		"reference": "34490",
		"description": "Voilage à illets Noa Bordeaux",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,44"
	},
	{
		"id": 98,
		"company": "DEMO Company",
		"reference": "34489",
		"description": "Voilage à illets Noa Beige",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,44"
	},
	{
		"id": 99,
		"company": "DEMO Company",
		"reference": "34488",
		"description": "Voilage à illets Tanja Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,4"
	},
	{
		"id": 100,
		"company": "DEMO Company",
		"reference": "34487",
		"description": "Voilage à illets Daphné Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,35"
	},
	{
		"id": 101,
		"company": "DEMO Company",
		"reference": "34486",
		"description": "Voilage à illets Elea Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,23"
	},
	{
		"id": 102,
		"company": "DEMO Company",
		"reference": "34485",
		"description": "Voilage à illets Elea Orange",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,23"
	},
	{
		"id": 103,
		"company": "DEMO Company",
		"reference": "34484",
		"description": "Voilage à illets Daphné Jaune",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,35"
	},
	{
		"id": 104,
		"company": "DEMO Company",
		"reference": "34483",
		"description": "Voilage à illets Elea Jaune",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,225"
	},
	{
		"id": 105,
		"company": "DEMO Company",
		"reference": "34482",
		"description": "Voilage à illets Tanja Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,4"
	},
	{
		"id": 106,
		"company": "DEMO Company",
		"reference": "34481",
		"description": "Voilage à illets Daphné Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,35"
	},
	{
		"id": 107,
		"company": "DEMO Company",
		"reference": "34480",
		"description": "Voilage à illets Hermes Taupe",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,47"
	},
	{
		"id": 108,
		"company": "DEMO Company",
		"reference": "34479",
		"description": "Voilage à illets Hermes Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,47"
	},
	{
		"id": 109,
		"company": "DEMO Company",
		"reference": "34478",
		"description": "Voilage à illets Hermes Ivoire",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,47"
	},
	{
		"id": 110,
		"company": "DEMO Company",
		"reference": "34477",
		"description": "Voilage à illets Hermes Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,47"
	},
	{
		"id": 111,
		"company": "DEMO Company",
		"reference": "34476",
		"description": "Voilage à illets Elea Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,23"
	},
	{
		"id": 112,
		"company": "DEMO Company",
		"reference": "34475",
		"description": "Voilage à illets Elea Gris Anthracite",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,23"
	},
	{
		"id": 113,
		"company": "DEMO Company",
		"reference": "34474",
		"description": "Voilage à illets Tanja Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,4"
	},
	{
		"id": 114,
		"company": "DEMO Company",
		"reference": "34473",
		"description": "Voilage à illets Daphné Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,35"
	},
	{
		"id": 115,
		"company": "DEMO Company",
		"reference": "34472",
		"description": "Voilage à illets Ambre Taupe et Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,36"
	},
	{
		"id": 116,
		"company": "DEMO Company",
		"reference": "34471",
		"description": "Voilage à illets Ambre Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,36"
	},
	{
		"id": 117,
		"company": "DEMO Company",
		"reference": "34470",
		"description": "Voilage à illets Ambre Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,36"
	},
	{
		"id": 118,
		"company": "DEMO Company",
		"reference": "34469",
		"description": "Voilage à illets Ambre Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,36"
	},
	{
		"id": 119,
		"company": "DEMO Company",
		"reference": "34468",
		"description": "Voilage à illets Iona Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,4"
	},
	{
		"id": 120,
		"company": "DEMO Company",
		"reference": "34467",
		"description": "Voilage à illets Tessa Prune",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,32"
	},
	{
		"id": 121,
		"company": "DEMO Company",
		"reference": "34466",
		"description": "Voilage à illets Tessa Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,32"
	},
	{
		"id": 122,
		"company": "DEMO Company",
		"reference": "34465",
		"description": "Voilage à illets Ines Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,47"
	},
	{
		"id": 123,
		"company": "DEMO Company",
		"reference": "34464",
		"description": "Voilage à illets Eline Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,41"
	},
	{
		"id": 124,
		"company": "DEMO Company",
		"reference": "34463",
		"description": "Voilage à illets Oriane Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,41"
	},
	{
		"id": 125,
		"company": "DEMO Company",
		"reference": "34462",
		"description": "Voilage à illets Tessa Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,32"
	},
	{
		"id": 126,
		"company": "DEMO Company",
		"reference": "34461",
		"description": "Voilage à illets Ines Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,47"
	},
	{
		"id": 127,
		"company": "DEMO Company",
		"reference": "34460",
		"description": "Voilage à illets Eline Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,41"
	},
	{
		"id": 128,
		"company": "DEMO Company",
		"reference": "34459",
		"description": "Voilage à illets Tessa Bambou",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,32"
	},
	{
		"id": 129,
		"company": "DEMO Company",
		"reference": "34458",
		"description": "Voilage à illets Helena Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,38"
	},
	{
		"id": 130,
		"company": "DEMO Company",
		"reference": "34457",
		"description": "Voilage à illets Helena Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,38"
	},
	{
		"id": 131,
		"company": "DEMO Company",
		"reference": "34456",
		"description": "Voilage à illets Anja Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,395"
	},
	{
		"id": 132,
		"company": "DEMO Company",
		"reference": "34455",
		"description": "Rideau à oeillets Helios Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,465"
	},
	{
		"id": 133,
		"company": "DEMO Company",
		"reference": "34454",
		"description": "Rideau à oeillets Daphne Taupe",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,88"
	},
	{
		"id": 134,
		"company": "DEMO Company",
		"reference": "34453",
		"description": "Rideau à oeillets Helena Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,895"
	},
	{
		"id": 135,
		"company": "DEMO Company",
		"reference": "34452",
		"description": "Rideau à oeillets Karla Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,72"
	},
	{
		"id": 136,
		"company": "DEMO Company",
		"reference": "34451",
		"description": "Rideau à oeillets Erika Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,775"
	},
	{
		"id": 137,
		"company": "DEMO Company",
		"reference": "34450",
		"description": "Rideau à oeillets Karla Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,72"
	},
	{
		"id": 138,
		"company": "DEMO Company",
		"reference": "34449",
		"description": "Rideau à oeillets Hanna Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,71"
	},
	{
		"id": 139,
		"company": "DEMO Company",
		"reference": "34448",
		"description": "Rideau à oeillets Daphne Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,88"
	},
	{
		"id": 140,
		"company": "DEMO Company",
		"reference": "34447",
		"description": "Rideau à oeillets Fifties Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "1,055"
	},
	{
		"id": 141,
		"company": "DEMO Company",
		"reference": "34446",
		"description": "Rideau à oeillets Fifties Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "1,06"
	},
	{
		"id": 142,
		"company": "DEMO Company",
		"reference": "34445",
		"description": "Rideau à oeillets Karla Chocolat",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,72"
	},
	{
		"id": 143,
		"company": "DEMO Company",
		"reference": "34444",
		"description": "Rideau à oeillets Hanna Bordeaux",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,71"
	},
	{
		"id": 144,
		"company": "DEMO Company",
		"reference": "34443",
		"description": "Rideau à oeillets Erika Bordeaux",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,775"
	},
	{
		"id": 145,
		"company": "DEMO Company",
		"reference": "34442",
		"description": "Rideau à oeillets Helena Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,895"
	},
	{
		"id": 146,
		"company": "DEMO Company",
		"reference": "34441",
		"description": "Rideau à oeillets Karla Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,72"
	},
	{
		"id": 147,
		"company": "DEMO Company",
		"reference": "34440",
		"description": "Rideau à oeillets Antigone Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,47"
	},
	{
		"id": 148,
		"company": "DEMO Company",
		"reference": "34439",
		"description": "Rideau à oeillets Stars Multicolore",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 32,
		"width": 23,
		"height": 5,
		"weight": "0,31"
	},
	{
		"id": 149,
		"company": "DEMO Company",
		"reference": "34438",
		"description": "Rideau à oeillets Iona Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,735"
	},
	{
		"id": 150,
		"company": "DEMO Company",
		"reference": "34437",
		"description": "Rideau à oeillets Iona Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 34,
		"width": 25,
		"height": 10,
		"weight": "0,735"
	},
	{
		"id": 151,
		"company": "DEMO Company",
		"reference": "34436",
		"description": "Coussin rectangulaire Helena Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 61,
		"width": 32,
		"height": 5,
		"weight": "0,565"
	},
	{
		"id": 152,
		"company": "DEMO Company",
		"reference": "34435",
		"description": "Coussin déhoussable Erika Bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 44,
		"width": 44,
		"height": 5,
		"weight": "0,51"
	},
	{
		"id": 153,
		"company": "DEMO Company",
		"reference": "34434",
		"description": "Coussin déhoussable Erika Bordeaux",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 44,
		"width": 44,
		"height": 5,
		"weight": "0,51"
	},
	{
		"id": 154,
		"company": "DEMO Company",
		"reference": "34433",
		"description": "Coussin rectangulaire Helena Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 61,
		"width": 32,
		"height": 5,
		"weight": "0,565"
	},
	{
		"id": 155,
		"company": "DEMO Company",
		"reference": "34432",
		"description": "COUVRE LIT TOSCANE2  90 gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 48,
		"width": 38,
		"height": 20,
		"weight": "4"
	},
	{
		"id": 156,
		"company": "DEMO Company",
		"reference": "34431",
		"description": "COUVRE LIT TOSCANE1  90 gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 48,
		"width": 38,
		"height": 20,
		"weight": "4"
	},
	{
		"id": 157,
		"company": "DEMO Company",
		"reference": "34430",
		"description": "RIDEAU MORGANE 37 orange",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 44,
		"width": 31,
		"height": 3,
		"weight": "1,9"
	},
	{
		"id": 158,
		"company": "DEMO Company",
		"reference": "34429",
		"description": "RIDEAU MORGANE 77 violine  prune",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 44,
		"width": 31,
		"height": 3,
		"weight": "1,9"
	},
	{
		"id": 159,
		"company": "DEMO Company",
		"reference": "34428",
		"description": "RIDEAU MORGANE 19 noir  gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 44,
		"width": 31,
		"height": 3,
		"weight": "1,9"
	},
	{
		"id": 160,
		"company": "DEMO Company",
		"reference": "34427",
		"description": "COUVRE LIT ZOE2 90 gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 48,
		"width": 38,
		"height": 20,
		"weight": "3"
	},
	{
		"id": 161,
		"company": "DEMO Company",
		"reference": "34426",
		"description": "COUVRE LIT ZOE1 90 gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 48,
		"width": 38,
		"height": 20,
		"weight": "3"
	},
	{
		"id": 162,
		"company": "DEMO Company",
		"reference": "34425",
		"description": "COUVRE LIT ZOE 70 violine",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 48,
		"width": 38,
		"height": 20,
		"weight": "3"
	},
	{
		"id": 163,
		"company": "DEMO Company",
		"reference": "34424",
		"description": "COUVRE LIT ZOE 40 bleu",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 48,
		"width": 38,
		"height": 20,
		"weight": "3"
	},
	{
		"id": 164,
		"company": "DEMO Company",
		"reference": "34423",
		"description": "RIDEAU BLUSH 70 violine",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 165,
		"company": "DEMO Company",
		"reference": "34422",
		"description": "RIDEAU BLUSH 19 gris nacre",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 166,
		"company": "DEMO Company",
		"reference": "34421",
		"description": "RIDEAU GRIBOUILLE  35 orange",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 167,
		"company": "DEMO Company",
		"reference": "34420",
		"description": "RIDEAU GRIBOUILLE  60 rose  anis",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 168,
		"company": "DEMO Company",
		"reference": "34419",
		"description": "RIDEAU GRIBOUILLE  90 gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 169,
		"company": "DEMO Company",
		"reference": "34418",
		"description": "RIDEAU JIMMY 19 noir  gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 170,
		"company": "DEMO Company",
		"reference": "34417",
		"description": "RIDEAU VESPA  45",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 39,
		"width": 27,
		"height": 3,
		"weight": "1,3"
	},
	{
		"id": 171,
		"company": "DEMO Company",
		"reference": "34416",
		"description": "VOILAGE DOUBLE COEUR2  90 gris  blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 172,
		"company": "DEMO Company",
		"reference": "34415",
		"description": "VOILAGE DOUBLE COEUR2  69 rouge  blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 173,
		"company": "DEMO Company",
		"reference": "34414",
		"description": "VOILAGE PAMPILLE 80 anis  beige",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 174,
		"company": "DEMO Company",
		"reference": "34413",
		"description": "VOILAGE PAMPILLE 70 violine",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 175,
		"company": "DEMO Company",
		"reference": "34412",
		"description": "VOILAGE PAMPILLE 60 rose  gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 176,
		"company": "DEMO Company",
		"reference": "34411",
		"description": "VOILAGE PAMPILLE 37 corail  gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 177,
		"company": "DEMO Company",
		"reference": "34410",
		"description": "VOILAGE PAMPILLE 28 beige  gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 178,
		"company": "DEMO Company",
		"reference": "34409",
		"description": "VOILAGE KAOLIN  93 gris anthracite",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 179,
		"company": "DEMO Company",
		"reference": "34408",
		"description": "VOILAGE KAOLIN  83 vert citron",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 180,
		"company": "DEMO Company",
		"reference": "34407",
		"description": "VOILAGE KAOLIN  37 safran",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 181,
		"company": "DEMO Company",
		"reference": "34406",
		"description": "VOILAGE KAOLIN  38 brique",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 182,
		"company": "DEMO Company",
		"reference": "34405",
		"description": "VOILAGE KAOLIN  67 fuchia",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 183,
		"company": "DEMO Company",
		"reference": "34404",
		"description": "VOILAGE KAOLIN  11 ecru",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 184,
		"company": "DEMO Company",
		"reference": "34403",
		"description": "VOILAGE DOUBLE COEUR1   90 gris  blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 185,
		"company": "DEMO Company",
		"reference": "34402",
		"description": "VOILAGE DOUBLE COEUR1   69 rouge  blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,8"
	},
	{
		"id": 186,
		"company": "DEMO Company",
		"reference": "34401",
		"description": "Rideau à oeillets Louis Blanc / Lin",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 40,
		"width": 27,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 187,
		"company": "DEMO Company",
		"reference": "34400",
		"description": "Rideau à oeillets Tornade Gris Clair",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 188,
		"company": "DEMO Company",
		"reference": "34399",
		"description": "Rideau à oeillets Smarties Noir Framboise",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 189,
		"company": "DEMO Company",
		"reference": "34398",
		"description": "Rideau à oeillets Smarties Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 190,
		"company": "DEMO Company",
		"reference": "34397",
		"description": "Rideau à oeillets Sunny Ecru",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 191,
		"company": "DEMO Company",
		"reference": "34396",
		"description": "Rideau à oeillets Sunny Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 192,
		"company": "DEMO Company",
		"reference": "34395",
		"description": "Rideau à oeillets Sunny Noir / Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 193,
		"company": "DEMO Company",
		"reference": "34394",
		"description": "Rideau à oeillets Campagne Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 40,
		"width": 27,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 194,
		"company": "DEMO Company",
		"reference": "34393",
		"description": "Rideau à oeillets occultant Frappé Quiétude Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "1"
	},
	{
		"id": 195,
		"company": "DEMO Company",
		"reference": "34392",
		"description": "Rideau à oeillets occultant Frappé Quiétude Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "1"
	},
	{
		"id": 196,
		"company": "DEMO Company",
		"reference": "34391",
		"description": "Rideau à oeillets occultant Frappé Quiétude Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "1"
	},
	{
		"id": 197,
		"company": "DEMO Company",
		"reference": "34390",
		"description": "Rideau à oeillets Graphic",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "1"
	},
	{
		"id": 198,
		"company": "DEMO Company",
		"reference": "34389",
		"description": "Rideau à oeillets Limousin Ecru Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 40,
		"width": 27,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 199,
		"company": "DEMO Company",
		"reference": "34388",
		"description": "Voilage à illets Linky Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 200,
		"company": "DEMO Company",
		"reference": "34387",
		"description": "Voilage à illets Linky Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 201,
		"company": "DEMO Company",
		"reference": "34386",
		"description": "Voilage à illets Ethnique Ecru / Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "0,96"
	},
	{
		"id": 202,
		"company": "DEMO Company",
		"reference": "34385",
		"description": "Rideau à oeillets Kingdom",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "1"
	},
	{
		"id": 203,
		"company": "DEMO Company",
		"reference": "34384",
		"description": "Rideau à oeillets States",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 28,
		"height": 3,
		"weight": "1"
	},
	{
		"id": 204,
		"company": "DEMO Company",
		"reference": "34383",
		"description": "Coussin brodé Louis Blanc et Lin",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,43"
	},
	{
		"id": 205,
		"company": "DEMO Company",
		"reference": "34382",
		"description": "Coussin déhoussable rectangulaire Campagne Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 51,
		"width": 31,
		"height": 4,
		"weight": "0,4"
	},
	{
		"id": 206,
		"company": "DEMO Company",
		"reference": "34381",
		"description": "Coussin déhoussable rectangulaire Londres",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 51,
		"width": 31,
		"height": 4,
		"weight": "0,36"
	},
	{
		"id": 207,
		"company": "DEMO Company",
		"reference": "34380",
		"description": "Coussin déhoussable Star",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,36"
	},
	{
		"id": 208,
		"company": "DEMO Company",
		"reference": "34379",
		"description": "Coussin déhoussable Comics",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 46,
		"width": 46,
		"height": 4,
		"weight": "0,5"
	},
	{
		"id": 209,
		"company": "DEMO Company",
		"reference": "34378",
		"description": "Coussin déhoussable rectangulaire Panda",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 56,
		"height": 4,
		"weight": "0,5"
	},
	{
		"id": 210,
		"company": "DEMO Company",
		"reference": "34377",
		"description": "Coussin déhoussable Bones",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,36"
	},
	{
		"id": 211,
		"company": "DEMO Company",
		"reference": "34376",
		"description": "Coussin déhoussable Paris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,36"
	},
	{
		"id": 212,
		"company": "DEMO Company",
		"reference": "34375",
		"description": "Galette de chaise Louis Blanc et Lin",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 5,
		"weight": "0,95"
	},
	{
		"id": 213,
		"company": "DEMO Company",
		"reference": "34374",
		"description": "Coussin déhoussable rectangulaire Graphic",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 51,
		"width": 31,
		"height": 4,
		"weight": "0,36"
	},
	{
		"id": 214,
		"company": "DEMO Company",
		"reference": "34373",
		"description": "Galette de chaise Campagne Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,95"
	},
	{
		"id": 215,
		"company": "DEMO Company",
		"reference": "34372",
		"description": "Coussin déhoussable Limousin Ecru Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,4"
	},
	{
		"id": 216,
		"company": "DEMO Company",
		"reference": "34371",
		"description": "Galette de chaise Kingdom",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,95"
	},
	{
		"id": 217,
		"company": "DEMO Company",
		"reference": "34370",
		"description": "Coussin rectangulaire Kingdom",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 51,
		"width": 31,
		"height": 4,
		"weight": "0,4"
	},
	{
		"id": 218,
		"company": "DEMO Company",
		"reference": "34369",
		"description": "Galette de chaise States",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,95"
	},
	{
		"id": 219,
		"company": "DEMO Company",
		"reference": "34368",
		"description": "Coussin déhoussable States",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,4"
	},
	{
		"id": 220,
		"company": "DEMO Company",
		"reference": "34367",
		"description": "Galette de chaise Limousin Ecru / Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 4,
		"weight": "0,95"
	},
	{
		"id": 221,
		"company": "DEMO Company",
		"reference": "34366",
		"description": "KIT BARRE CARREE 60 CM+DOUCHETTE RECTANGULAIRE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,42"
	},
	{
		"id": 222,
		"company": "DEMO Company",
		"reference": "34365",
		"description": "ABATTANT WC THERMODURE + CHUTE DE FREIN - BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "2"
	},
	{
		"id": 223,
		"company": "DEMO Company",
		"reference": "34364",
		"description": "Abattant WC Chien lunettes Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "2,5"
	},
	{
		"id": 224,
		"company": "DEMO Company",
		"reference": "34363",
		"description": "ABATTANT WC MDF - BRAZIL",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "2,5"
	},
	{
		"id": 225,
		"company": "DEMO Company",
		"reference": "34362",
		"description": "ABATTANT WC MDF - ROMANCE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "2,5"
	},
	{
		"id": 226,
		"company": "DEMO Company",
		"reference": "34361",
		"description": "RIDEAU DE DOUCHE POLYESTER 180x200 CM - ROMANCE FOND TAUPE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,46"
	},
	{
		"id": 227,
		"company": "DEMO Company",
		"reference": "34360",
		"description": "RIDEAU DE DOUCHE POLYESTER 180x200 CM - ROMANCE FOND BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,46"
	},
	{
		"id": 228,
		"company": "DEMO Company",
		"reference": "34359",
		"description": "PORTE SERVIETTE 1 BARRE 59 CM A FIXER ZAMACK",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,001"
	},
	{
		"id": 229,
		"company": "DEMO Company",
		"reference": "34358",
		"description": "POUBELLE METAL IMPRIMEE 3L - KARAMEL",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,65"
	},
	{
		"id": 230,
		"company": "DEMO Company",
		"reference": "34357",
		"description": "Tapis de bain Romance Taupe",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,26"
	},
	{
		"id": 231,
		"company": "DEMO Company",
		"reference": "34356",
		"description": "PORTE SERVIETTE FORME ARRONDIE A FIXER ZAMACK",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,001"
	},
	{
		"id": 232,
		"company": "DEMO Company",
		"reference": "34355",
		"description": "DEROULEUR PAPIER WC A FIXER ZAMACK / ACIER INOXIDABLE  - CHROME",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,001"
	},
	{
		"id": 233,
		"company": "DEMO Company",
		"reference": "34354",
		"description": "ABATTANT WC MOUSSE - ROMANCE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "1,08"
	},
	{
		"id": 234,
		"company": "DEMO Company",
		"reference": "34353",
		"description": "PATERE METAL 8 CROCHETS - CHROME/BOIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,56"
	},
	{
		"id": 235,
		"company": "DEMO Company",
		"reference": "34352",
		"description": "PATERE METAL 8 CROCHETS - CHROME/GRIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,56"
	},
	{
		"id": 236,
		"company": "DEMO Company",
		"reference": "34351",
		"description": "PATERE METAL 8 CROCHETS - CHROME/BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,44"
	},
	{
		"id": 237,
		"company": "DEMO Company",
		"reference": "34350",
		"description": "Tapis de bain Romance Ecru",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,36"
	},
	{
		"id": 238,
		"company": "DEMO Company",
		"reference": "34349",
		"description": "Tapis contour WC Romance Taupe",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,16"
	},
	{
		"id": 239,
		"company": "DEMO Company",
		"reference": "34348",
		"description": "Brosse de toilettes WC Chien Marron",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,35"
	},
	{
		"id": 240,
		"company": "DEMO Company",
		"reference": "34347",
		"description": "REDUCTEUR WC ENFANT MOUSSE AVEC POIGNEES -  ENFANTINE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,33"
	},
	{
		"id": 241,
		"company": "DEMO Company",
		"reference": "34346",
		"description": "DEROULEUR PAPIER WC MDF - KARAMEL",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,32"
	},
	{
		"id": 242,
		"company": "DEMO Company",
		"reference": "34345",
		"description": "DEROULEUR PAPIER WC MDF - BRAZIL",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,32"
	},
	{
		"id": 243,
		"company": "DEMO Company",
		"reference": "34344",
		"description": "DISTRIBUTEUR A SAVON ACIER INOXYDABLE MARTELE - CHROME",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,1"
	},
	{
		"id": 244,
		"company": "DEMO Company",
		"reference": "34343",
		"description": "PATERE DOUBLE CROCHET A FIXER ZAMACK",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,001"
	},
	{
		"id": 245,
		"company": "DEMO Company",
		"reference": "34342",
		"description": "RIDEAU DE DOUCHE PEVA 180 x 180 CM  - ROMANCE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,35"
	},
	{
		"id": 246,
		"company": "DEMO Company",
		"reference": "34341",
		"description": "PATERE  A FIXER ZAMACK / ACIER INOXYDABLE - CHROME",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,001"
	},
	{
		"id": 247,
		"company": "DEMO Company",
		"reference": "34340",
		"description": "PANIERE OSIER ROND AVEC COUVERCLE - GRIS/TISSU LIN",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,15"
	},
	{
		"id": 248,
		"company": "DEMO Company",
		"reference": "34339",
		"description": "BROSSE WC PP IMPRIMEE - ROMANCE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,16"
	},
	{
		"id": 249,
		"company": "DEMO Company",
		"reference": "34338",
		"description": "PANIER OSIER  AVEC ANSES - GRIS/TISSU LIN",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,15"
	},
	{
		"id": 250,
		"company": "DEMO Company",
		"reference": "34337",
		"description": "POUBELLE PP IMPRIMEE -  ROMANCE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,2"
	},
	{
		"id": 251,
		"company": "DEMO Company",
		"reference": "34336",
		"description": "PATERE INCURVEE A FIXER ZAMACK  - CHROME",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,001"
	},
	{
		"id": 252,
		"company": "DEMO Company",
		"reference": "34335",
		"description": "GOBELET ACIER INOXYDABLE MARTELE - CHROME",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,05"
	},
	{
		"id": 253,
		"company": "DEMO Company",
		"reference": "34334",
		"description": "SET DE 4 FONDS DE DOUCHE COCHON/OURS/CANARD/CHAT -  ENFANTINE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,03"
	},
	{
		"id": 254,
		"company": "DEMO Company",
		"reference": "34333",
		"description": "SET DE 4 FONDS DE DOUCHE PIEUVRE/POISSON",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,03"
	},
	{
		"id": 255,
		"company": "DEMO Company",
		"reference": "34332",
		"description": "PORTE SAVON ROND ACIER INOXYDABLE MARTELE - CHROME",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,1"
	},
	{
		"id": 256,
		"company": "DEMO Company",
		"reference": "34331",
		"description": "PORTE SERVIETTE PP FORME ARRONDIE SUR VENTOUSES - BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,11"
	},
	{
		"id": 257,
		"company": "DEMO Company",
		"reference": "34330",
		"description": "DOUBLE CROCHET METAL 1 VENTOUSE + 1 DECO - DIAMANT GRIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,04"
	},
	{
		"id": 258,
		"company": "DEMO Company",
		"reference": "34329",
		"description": "DOUBLE CROCHET METAL 1 VENTOUSE + 1 DECO - GALET BLEU",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,1"
	},
	{
		"id": 259,
		"company": "DEMO Company",
		"reference": "34328",
		"description": "DOUBLE CROCHET METAL 1 VENTOUSE + 1 DECO - GALET GRIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,1"
	},
	{
		"id": 260,
		"company": "DEMO Company",
		"reference": "34327",
		"description": "PORTE RASOIR PP SUR VENTOUSE - BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,04"
	},
	{
		"id": 261,
		"company": "DEMO Company",
		"reference": "34326",
		"description": "SET DE 2 CROCHETS  PROMO PP SUR VENTOUSES -  GRIS",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,06"
	},
	{
		"id": 262,
		"company": "DEMO Company",
		"reference": "34325",
		"description": "SET DE 2 CROCHETS  PROMO PP SUR VENTOUSES -  TAUPE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,06"
	},
	{
		"id": 263,
		"company": "DEMO Company",
		"reference": "34324",
		"description": "SET DE 2 CROCHETS  PROMO PP SUR VENTOUSES -  NOIR",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 0,
		"width": 0,
		"height": 0,
		"weight": "0,06"
	},
	{
		"id": 264,
		"company": "DEMO Company",
		"reference": "34323",
		"description": "Rideau à oeillets occultant Melodie à Pois Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 3,
		"weight": "0,8"
	},
	{
		"id": 265,
		"company": "DEMO Company",
		"reference": "34322",
		"description": "Rideau à oeillets occultant Melodie à Pois Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 3,
		"weight": "0,8"
	},
	{
		"id": 266,
		"company": "DEMO Company",
		"reference": "34321",
		"description": "Rideau à oeillets occultant Melodie à Pois Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 3,
		"weight": "0,8"
	},
	{
		"id": 267,
		"company": "DEMO Company",
		"reference": "34320",
		"description": "Rideau à oeillets Feuillage Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 268,
		"company": "DEMO Company",
		"reference": "34319",
		"description": "Rideau à oeillets Feuillage Anis",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 269,
		"company": "DEMO Company",
		"reference": "34318",
		"description": "Rideau à oeillets Feuillage Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 270,
		"company": "DEMO Company",
		"reference": "34317",
		"description": "Rideau à oeillets Rayure Noir et Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 271,
		"company": "DEMO Company",
		"reference": "34316",
		"description": "Rideau à oeillets Rayure Violet et Rose",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 272,
		"company": "DEMO Company",
		"reference": "34315",
		"description": "Tête de lit (70 cm) Capiton Taupe",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 273,
		"company": "DEMO Company",
		"reference": "34314",
		"description": "Tête de lit (70 cm) Capiton Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 274,
		"company": "DEMO Company",
		"reference": "34313",
		"description": "Tête de lit (70 cm) Capiton Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 275,
		"company": "DEMO Company",
		"reference": "34312",
		"description": "Tête de lit (70 cm) Capiton Naturel",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 276,
		"company": "DEMO Company",
		"reference": "34311",
		"description": "Tête de lit (70 cm) Capiton Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 277,
		"company": "DEMO Company",
		"reference": "34310",
		"description": "Tête de lit (70 cm) Capiton Fuchsia",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 278,
		"company": "DEMO Company",
		"reference": "34309",
		"description": "Tête de lit (70 cm) Capiton Ecru",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 279,
		"company": "DEMO Company",
		"reference": "34308",
		"description": "Tête de lit (70 cm) Capiton Chocolat",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 70,
		"width": 50,
		"height": 10,
		"weight": "1,1"
	},
	{
		"id": 280,
		"company": "DEMO Company",
		"reference": "34307",
		"description": "Voilage à oeillets Melodie à Pois Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 281,
		"company": "DEMO Company",
		"reference": "34306",
		"description": "Voilage à oeillets Melodie à Pois Gris Foncé",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 282,
		"company": "DEMO Company",
		"reference": "34305",
		"description": "Voilage à oeillets Melodie à Pois Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 27,
		"height": 2,
		"weight": "0,06"
	},
	{
		"id": 283,
		"company": "DEMO Company",
		"reference": "34304",
		"description": "Tapis de cuisine (80 cm) imprimé Poule",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 50,
		"height": 3,
		"weight": "0,6"
	},
	{
		"id": 284,
		"company": "DEMO Company",
		"reference": "34303",
		"description": "Tapis de cuisine (80 cm) imprimé Coquelicot",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 50,
		"height": 3,
		"weight": "0,6"
	},
	{
		"id": 285,
		"company": "DEMO Company",
		"reference": "34302",
		"description": "Tapis de cuisine (80 cm) imprimé Potiron",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 50,
		"height": 3,
		"weight": "0,6"
	},
	{
		"id": 286,
		"company": "DEMO Company",
		"reference": "34301",
		"description": "Tapis de cuisine (80 cm) imprimé Galet",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 38,
		"width": 50,
		"height": 3,
		"weight": "0,6"
	},
	{
		"id": 287,
		"company": "DEMO Company",
		"reference": "34300",
		"description": "Coussin déhoussable Rayure Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 8,
		"weight": "0,5"
	},
	{
		"id": 288,
		"company": "DEMO Company",
		"reference": "34299",
		"description": "Coussin déhoussable Rayure Violet",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 8,
		"weight": "0,5"
	},
	{
		"id": 289,
		"company": "DEMO Company",
		"reference": "34298",
		"description": "Coussin déhoussable Feuillage Rouge",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 8,
		"weight": "0,5"
	},
	{
		"id": 290,
		"company": "DEMO Company",
		"reference": "34297",
		"description": "Coussin déhoussable Feuillage Anis",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 8,
		"weight": "0,5"
	},
	{
		"id": 291,
		"company": "DEMO Company",
		"reference": "34296",
		"description": "Coussin déhoussable Feuillage Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 41,
		"width": 41,
		"height": 8,
		"weight": "0,5"
	},
	{
		"id": 292,
		"company": "DEMO Company",
		"reference": "34295",
		"description": "Kit extensible (L380 cm  D19 mm) Champignon Or",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 293,
		"company": "DEMO Company",
		"reference": "34294",
		"description": "Kit extensible (L380 cm  D19 mm) Feuille Bronze",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 294,
		"company": "DEMO Company",
		"reference": "34293",
		"description": "Kit extensible (L380 cm  D19 mm) Amande Graphite",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 295,
		"company": "DEMO Company",
		"reference": "34292",
		"description": "Kit extensible (L380 cm  D19 mm) Amande Chrome",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 296,
		"company": "DEMO Company",
		"reference": "34291",
		"description": "Kit extensible (L380 cm  D19 mm) Amande Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 297,
		"company": "DEMO Company",
		"reference": "34290",
		"description": "Kit extensible (L380 cm  D19 mm) Cubique Graphite",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 298,
		"company": "DEMO Company",
		"reference": "34289",
		"description": "Kit extensible (L380 cm  D19 mm) Cubique Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 8,
		"height": 250,
		"weight": "1,4"
	},
	{
		"id": 299,
		"company": "DEMO Company",
		"reference": "34288",
		"description": "Kit extensible (L380 cm  D19 mm) Ovale Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 300,
		"company": "DEMO Company",
		"reference": "34287",
		"description": "Kit extensible (L380 cm  D19 mm) Ovale Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 301,
		"company": "DEMO Company",
		"reference": "34286",
		"description": "Kit extensible (L380 cm  D19 mm) Strass Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 302,
		"company": "DEMO Company",
		"reference": "34285",
		"description": "Kit extensible (L210 cm  D19 mm) Champignon Or",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 303,
		"company": "DEMO Company",
		"reference": "34284",
		"description": "Kit extensible (L210 cm  D19 mm) Feuille Bronze",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 304,
		"company": "DEMO Company",
		"reference": "34283",
		"description": "Kit extensible (L210 cm  D19 mm) Amande Graphite",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 305,
		"company": "DEMO Company",
		"reference": "34282",
		"description": "Kit extensible (L210 cm  D19 mm) Amande Chrome",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 306,
		"company": "DEMO Company",
		"reference": "34281",
		"description": "Kit extensible (L210 cm  D19 mm) Amande Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 307,
		"company": "DEMO Company",
		"reference": "34280",
		"description": "Kit extensible (L210 cm  D19 mm) Cubique Graphite",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 308,
		"company": "DEMO Company",
		"reference": "34279",
		"description": "Kit extensible (L210 cm  D19 mm) Cubique Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,17"
	},
	{
		"id": 309,
		"company": "DEMO Company",
		"reference": "34278",
		"description": "STORE ENROULEUR PVC 150X180CM - TAUPE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 156,
		"width": 10,
		"height": 4,
		"weight": "2,85"
	},
	{
		"id": 310,
		"company": "DEMO Company",
		"reference": "34277",
		"description": "STORE ENROULEUR PVC 150X180CM - BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 156,
		"width": 10,
		"height": 4,
		"weight": "2,85"
	},
	{
		"id": 311,
		"company": "DEMO Company",
		"reference": "34276",
		"description": "Kit extensible (L380 cm  D19 mm) Geometrique Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 312,
		"company": "DEMO Company",
		"reference": "34275",
		"description": "Kit extensible (L380 cm  D19 mm) Geometrique Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 313,
		"company": "DEMO Company",
		"reference": "34274",
		"description": "Kit extensible (L380 cm  D19 mm) Geometrique Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 314,
		"company": "DEMO Company",
		"reference": "34273",
		"description": "Kit extensible (L380 cm  D19 mm) Boule Noir et Argent",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 315,
		"company": "DEMO Company",
		"reference": "34272",
		"description": "Kit extensible (L380 cm  D19 mm) Boule Gris",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 316,
		"company": "DEMO Company",
		"reference": "34271",
		"description": "Kit extensible (L380 cm  D19 mm) Boule Rouille et Or",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 250,
		"weight": "1,75"
	},
	{
		"id": 317,
		"company": "DEMO Company",
		"reference": "34270",
		"description": "Kit extensible (L210 cm  D19 mm) Ovale Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,184"
	},
	{
		"id": 318,
		"company": "DEMO Company",
		"reference": "34269",
		"description": "Kit extensible (L210 cm  D19 mm) Ovale Blanc",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,184"
	},
	{
		"id": 319,
		"company": "DEMO Company",
		"reference": "34268",
		"description": "Kit extensible (L210 cm  D19 mm) Strass Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,184"
	},
	{
		"id": 320,
		"company": "DEMO Company",
		"reference": "34267",
		"description": "STORE ENROULEUR PVC 120X180CM - TAUPE",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 126,
		"width": 10,
		"height": 4,
		"weight": "2,633"
	},
	{
		"id": 321,
		"company": "DEMO Company",
		"reference": "34266",
		"description": "STORE ENROULEUR PVC 120X180CM - BLANC",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 126,
		"width": 10,
		"height": 4,
		"weight": "2,633"
	},
	{
		"id": 322,
		"company": "DEMO Company",
		"reference": "34265",
		"description": "Kit extensible (L210 cm  D19 mm) Geometrique Noir",
		"piece-to-be-replenish": "Yes",
		"status": "IN PROGRESS",
		"length": 10,
		"width": 5,
		"height": 153,
		"weight": "1,184"
	}
 ]