export const equipmentsData = [
  {
    "id":1,
    "priority": 1,
    "type": "Trolley multi",
    "name": "Chariot 15",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 15,
    "check-position": "Yes"
  },
  {
    "id":2,
    "priority": 2,
    "type": "Trolley mono",
    "name": "Chariot mono",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 30,
    "check-position": "No"
  },
  {
    "id":3,
    "priority": 3,
    "type": "Trolley multi",
    "name": "Chariot 7",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 7,
    "check-position": "Yes"
  },
  {
    "id":4,
    "priority": 4,
    "type": "Trolley multi",
    "name": "Chariot 4",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 4,
    "check-position": "Yes"
  },
  {
    "id":5,
    "priority": 5,
    "type": "Trolley multi",
    "name": "Chariot 2",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 2,
    "check-position": "Yes"
  },
  {
    "id":6,
    "priority": 6,
    "type": "Trolley multi",
    "name": "Chariot 3",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 3,
    "check-position": "Yes"
  },
  {
    "id":7,
    "priority": 7,
    "type": "Trolley mono",
    "name": "Chariot mono Lourd",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "No",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 15,
    "check-position": "No"
  },
  {
    "id":8,
    "priority": 8,
    "type": "Trolley multi",
    "name": "Chariot lourd",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "No",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 5,
    "check-position": "No"
  },
  {
    "id":9,
    "priority": 9,
    "type": "Trolley mono",
    "name": "Chariot mono Hors Gab",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 10,
    "check-position": "No"
  },
  {
    "id":10,
    "priority": 10,
    "type": "Trolley multi",
    "name": "Grosse commande",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 1,
    "check-position": "No"
  },
  {
    "id":11,
    "priority": 11,
    "type": "Trolley mono",
    "name": "Chariot SAV",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "Yes",
    "mono-carrier": "No",
    "nb-max-box": 10,
    "check-position": "No"
  },
  {
    "id":12,
    "priority": 12,
    "type": "Trolley multi",
    "name": "Chariot 5",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "Yes",
    "nb-max-box": 5,
    "check-position": "Yes"
  },
  {
    "id":13,
    "priority": 13,
    "type": "Trolley mono",
    "name": "Chariot palette",
    "status": "IN PROGRESS",
    "available": "Yes",
    "distributed": "Yes",
    "mono-company": "No",
    "mono-carrier": "No",
    "nb-max-box": 1,
    "check-position": "No"
  }
]