export const settingsData = [{
  "id": 1,
  "param-category": "configuration",
  "name": "radio_display_warehouse_code",
  "value": 31,
  "system": "yes"
}, {
  "id": 2,
  "param-category": "stock_management",
  "name": "product_printer_type",
  "value": 18,
  "system": "yes"
}, {
  "id": 3,
  "param-category": "printout",
  "name": "prepare_edi_file_trigger",
  "value": 6,
  "system": "no"
}, {
  "id": 4,
  "param-category": "stock_management",
  "name": "packaging_printer_orientation",
  "value": 86,
  "system": "yes"
}, {
  "id": 5,
  "param-category": "printout",
  "name": "packaging_pdf_destination",
  "value": 93,
  "system": "no"
}, {
  "id": 6,
  "param-category": "printout",
  "name": "location_printer_type",
  "value": 23,
  "system": "no"
}, {
  "id": 7,
  "param-category": "configuration",
  "name": "load_pdf_destination",
  "value": 2,
  "system": "yes"
}, {
  "id": 8,
  "param-category": "printout",
  "name": "load_label_printer_orientation",
  "value": 46,
  "system": "no"
}, {
  "id": 9,
  "param-category": "printout",
  "name": "load_label_pdf_destination",
  "value": 12,
  "system": "no"
}, {
  "id": 10,
  "param-category": "printout",
  "name": "equipment_printer_type",
  "value": 41,
  "system": "yes"
}, {
  "id": 11,
  "param-category": "printout",
  "name": "equipment_printer_orientation",
  "value": 6,
  "system": "no"
}, {
  "id": 12,
  "param-category": "stock_management",
  "name": "equipment_pdf_destination",
  "value": 74,
  "system": "yes"
}, {
  "id": 13,
  "param-category": "stock_management",
  "name": "box_printer_type",
  "value": 91,
  "system": "yes"
}, {
  "id": 14,
  "param-category": "configuration",
  "name": "avoid_partial_shipment",
  "value": 19,
  "system": "no"
}, {
  "id": 15,
  "param-category": "configuration",
  "name": "auto_print_equipment_label",
  "value": 53,
  "system": "yes"
}, {
  "id": 16,
  "param-category": "stock_management",
  "name": "round_location_sort",
  "value": 33,
  "system": "yes"
}, {
  "id": 17,
  "param-category": "stock_management",
  "name": "force_print_labels_no_scan_position",
  "value": 75,
  "system": "no"
}, {
  "id": 18,
  "param-category": "printout",
  "name": "equipment",
  "value": 22,
  "system": "no"
}, {
  "id": 19,
  "param-category": "configuration",
  "name": "automatic_box_control_validate",
  "value": 75,
  "system": "no"
}, {
  "id": 20,
  "param-category": "preparation_management",
  "name": "replen_nb_days_rotation_c",
  "value": 89,
  "system": "no"
}, {
  "id": 21,
  "param-category": "preparation_management",
  "name": "replen_nb_days_rotation_b",
  "value": 48,
  "system": "no"
}, {
  "id": 22,
  "param-category": "preparation_management",
  "name": "replen_nb_days_rotation_a",
  "value": 9,
  "system": "yes"
}, {
  "id": 23,
  "param-category": "configuration",
  "name": "replen_delta_percentage",
  "value": 43,
  "system": "yes"
}, {
  "id": 24,
  "param-category": "configuration",
  "name": "location_barcode_generic",
  "value": 38,
  "system": "no"
}, {
  "id": 25,
  "param-category": "preparation_management",
  "name": "id_bloc_error",
  "value": 97,
  "system": "yes"
}, {
  "id": 26,
  "param-category": "printout",
  "name": "id_adr_transit",
  "value": 44,
  "system": "no"
}, {
  "id": 27,
  "param-category": "configuration",
  "name": "id_adr_reintegration",
  "value": 5,
  "system": "no"
}, {
  "id": 28,
  "param-category": "stock_management",
  "name": "id_adr_reception",
  "value": 74,
  "system": "no"
}, {
  "id": 29,
  "param-category": "stock_management",
  "name": "id_adr_error",
  "value": 42,
  "system": "yes"
}, {
  "id": 30,
  "param-category": "configuration",
  "name": "goods_in_multi_purchase_order",
  "value": 49,
  "system": "no"
}, {
  "id": 31,
  "param-category": "preparation_management",
  "name": "content_export_feature",
  "value": 7,
  "system": "yes"
}, {
  "id": 32,
  "param-category": "configuration",
  "name": "wms_version",
  "value": 63,
  "system": "no"
}, {
  "id": 33,
  "param-category": "stock_management",
  "name": "warehouse_default",
  "value": 91,
  "system": "no"
}, {
  "id": 34,
  "param-category": "preparation_management",
  "name": "location_separator",
  "value": 6,
  "system": "no"
}, {
  "id": 35,
  "param-category": "preparation_management",
  "name": "location_mono_feature",
  "value": 23,
  "system": "yes"
}, {
  "id": 36,
  "param-category": "stock_management",
  "name": "language_xml_tags",
  "value": 41,
  "system": "no"
}, {
  "id": 37,
  "param-category": "printout",
  "name": "language_default",
  "value": 52,
  "system": "yes"
}, {
  "id": 38,
  "param-category": "preparation_management",
  "name": "id_company_default",
  "value": 7,
  "system": "no"
}, {
  "id": 39,
  "param-category": "printout",
  "name": "display_service_filter",
  "value": 56,
  "system": "no"
}, {
  "id": 40,
  "param-category": "printout",
  "name": "debug",
  "value": 38,
  "system": "no"
}]
