export const usersData = [{
  "id": 1,
  "username": "Alick",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 2,
  "username": "Dare",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 3,
  "username": "Kathi",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 4,
  "username": "Colin",
  "group": "Administrator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 5,
  "username": "Dilly",
  "group": "operator",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 6,
  "username": "Isac",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 7,
  "username": "Jessamine",
  "group": "Administrator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 8,
  "username": "Aldon",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": false
}, {
  "id": 9,
  "username": "Ynes",
  "group": "operator",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 10,
  "username": "Kore",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": false
}, {
  "id": 11,
  "username": "Herb",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 12,
  "username": "Pearl",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 13,
  "username": "Mohammed",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 14,
  "username": "Paulette",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 15,
  "username": "Tiebold",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 16,
  "username": "Osborn",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 17,
  "username": "Morton",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 18,
  "username": "Niki",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": false
}, {
  "id": 19,
  "username": "Van",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 20,
  "username": "Raimondo",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 21,
  "username": "Sheryl",
  "group": "Administrator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": false
}, {
  "id": 22,
  "username": "Troy",
  "group": "operator",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 23,
  "username": "Kearney",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 24,
  "username": "Benedicta",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 25,
  "username": "Anabelle",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 26,
  "username": "Fayth",
  "group": "operator",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": true
}, {
  "id": 27,
  "username": "Ida",
  "group": "operator",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 28,
  "username": "Alyse",
  "group": "operator",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": false
}, {
  "id": 29,
  "username": "Elmira",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 30,
  "username": "Milicent",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 31,
  "username": "Christos",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": false,
  "prep": true
}, {
  "id": 32,
  "username": "Flemming",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 33,
  "username": "Creigh",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 34,
  "username": "Billie",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 35,
  "username": "Silvia",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": false,
  "prep": false
}, {
  "id": 36,
  "username": "Abelard",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 37,
  "username": "Bebe",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 38,
  "username": "Shoshanna",
  "group": "operator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 39,
  "username": "Livvyy",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 40,
  "username": "Joelie",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": true
}, {
  "id": 41,
  "username": "Idell",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 42,
  "username": "Meier",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 43,
  "username": "Elka",
  "group": "Administrator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 44,
  "username": "Jolyn",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 45,
  "username": "Lucias",
  "group": "operator",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": true
}, {
  "id": 46,
  "username": "Onfroi",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 47,
  "username": "Ettore",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 48,
  "username": "Cathi",
  "group": "operator",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 49,
  "username": "Jedidiah",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 50,
  "username": "Farris",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": false
}, {
  "id": 51,
  "username": "Margalit",
  "group": "prepers",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 52,
  "username": "Lorilee",
  "group": "prepers",
  "status": "CLOSED",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 53,
  "username": "Karla",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": false,
  "ope": true,
  "prep": false
}, {
  "id": 54,
  "username": "Hugh",
  "group": "prepers",
  "status": "IN PROGRESS",
  "admin": true,
  "ope": true,
  "prep": false
}, {
  "id": 55,
  "username": "Antonie",
  "group": "operator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": true
}, {
  "id": 56,
  "username": "Fionna",
  "group": "operator",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 57,
  "username": "Arleta",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}, {
  "id": 58,
  "username": "Carlee",
  "group": "operator",
  "status": "CLOSED",
  "admin": false,
  "ope": false,
  "prep": false
}, {
  "id": 59,
  "username": "Spike",
  "group": "operator",
  "status": "CLOSED",
  "admin": true,
  "ope": false,
  "prep": false
}, {
  "id": 60,
  "username": "Danell",
  "group": "Administrator",
  "status": "CLOSED",
  "admin": false,
  "ope": true,
  "prep": true
}]

