/**
CELLA Frontend
Website and Mobile templates that can be used to communicate
with CELLA WMS APIs.
Copyright (C) 2023 KLOCEL <contact@klocel.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
**/
import { ModelType } from './Models';
import { Table } from 'generated/graphql';

export const MovementModel: ModelType = {
    tableName: Table.Movement,
    resolverName: 'Movement',

    endpoints: {
        list: 'movements',
        detail: 'movement',
        create: 'createMovement',
        update: 'updateMovement',
        delete: 'deleteMovement'
    },
    detailFields: [
        'id',
        'number',
        'stockOwnerId',
        'stockOwner{name}',
        'status',
        'statusText',
        'model',
        'modelText',
        'type',
        'typeText',
        'code',
        'codeText',
        'articleId',
        'article{name}',
        'article{additionalDescription}',
        'quantity',
        'initialStatus',
        'initialStatusText',
        'finalStatus',
        'finalStatusText',
        'initialReservation',
        'finalReservation',
        'finalArticle',
        'finalQuantity',
        'originalLocationId',
        'originalLocation{name}',
        'finalLocationId',
        'finalLocation{name}',
        'originalHandlingUnitId',
        'originalHandlingUnit{name}',
        'finalHandlingUnitId',
        'finalHandlingUnit{name}',
        'handlingUnitInboundName',
        'handlingUnitOutboundName',
        'purchaseOrderId',
        'purchaseOrder{name}',
        'returnCode',
        'returnCodeText',
        'actionCode',
        'actionCodeText',
        'comment',
        'feedback',
        'created',
        'createdBy',
        'modified',
        'modifiedBy'
    ],

    listFields: [
        'id',
        'number',
        'stockOwnerId',
        'stockOwner{name}',
        'status',
        'statusText',
        'originalHandlingUnitId',
        'finalHandlingUnitId',
        'model',
        'modelText',
        'type',
        'typeText',
        'code',
        'codeText',
        'articleId',
        'article{description}',
        'comment',
        'article{name}',
        'quantity',
        'originalLocation{name}',
        'finalLocationId',
        'finalLocation{name}',
        'originalContentId',
        'purchaseOrderId',
        'originalHandlingUnit{name}',
        'finalHandlingUnit{name}',
        'created',
        'createdBy',
        'modified',
        'modifiedBy'
    ],
    sortableFields: [
        'id',
        'stockOwner_name',
        'originalHandlingUnit_name',
        'finalHandlingUnit_name',
        'article_name',
        'modelText',
        'quantity',
        'finalLocation_name',
        'originalLocation_name',
        'originalContent_reservation',
        'typeText',
        'codeText',
        'comment',
        'number',
        'statusText',
        'feedback',
        'created',
        'createdBy',
        'modified',
        'modifiedBy'
    ],
    excludedDetailFields: [
        'id',
        'stockOwnerId',
        'status',
        'model',
        'handlingUnitId',
        'type',
        'code',
        'articleId',
        'initialStatus',
        'finalStatus',
        'originalLocationId',
        'finalLocationId',
        'handlingUnitOutboundId',
        'handlingUnitContentOutboundId',
        'goodsInId',
        'purchaseOrderId',
        'boxId',
        'boxLineId',
        'equipmentId',
        'originalMouvementId',
        'returnCode',
        'actionCode'
    ],
    excludedListFields: [
        'id',
        'stockOwnerId',
        'originalHandlingUnitId',
        'finalHandlingUnitId',
        'status',
        'model',
        'type',
        'code',
        'articleId',
        'initialStatus',
        'originalLocationId',
        'finalLocationId',
        'goodsInId',
        'purchaseOrderId',
        'boxId',
        'boxLineId',
        'originalContentId',
        'equipmentId',
        'originalMouvementId',
        'returnCode',
        'actionCode'
    ],
    hiddenListFields: [
        'stockOwnerId',
        'status',
        'type',
        'code',
        'articleId',
        'originalLocationId',
        'finalLocationId',
        'goodsInId',
        'purchaseOrderId',
        'boxId',
        'boxLineId',
        'equipmentId',
        'originalMouvementId',
        'returnCode',
        'actionCode',
        'created',
        'createdBy',
        'modified',
        'modifiedBy'
    ]
};
